### ISSUE TITLE
Build is broken, needs these fixes

### ISSUE THREAD

**Issue by dalbert2** [wizhippo/stm32f4-chibios-lwip-pppos#1]
In sysinfo.c, change call to chCoreStatus() to chCoreGetStatusX()

In Makefile, 
  1) change CSRC path to chprintf to $(CHIBIOS)/os/hal/lib/streams/chprintf.c
  2) Add $(CHIBIOS)/os/hal/lib/streams \ to INCDIR path

**Comment by wizhippo** [comment]
using latest ChibiOS now.  Thanks for the heads up
